1. (5 Points) Write a Python/NumPy code block that finds the distinct array items that exist in either array a or array b
but which do not appear within both arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Find the unique elements in each array
unique_a = np.unique(a)
unique_b = np.unique(b)

# Find elements that are unique to array a and array b
only_in_a = np.setdiff1d(unique_a, unique_b)
only_in_b = np.setdiff1d(unique_b, unique_a)

# Concatenate the unique elements and display them
unique_elements = np.concatenate((only_in_a, only_in_b))
unique_elements

array([ 1,  3,  5,  6,  7,  8,  9, 10])

2. (5 Points) Create the following 4x5 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.


In [ ]:
# Create a 1D array from 1 to 20
sequence = np.arange(1, 21)

# Reshape it to a 5x4 matrix and then transpose it to get a 4x5 matrix
desired_array = sequence.reshape((5, 4)).T
desired_array


array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

3. (5 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])
Write a Python/Numpy code block that adds to array a any items that are present in array b but not already present
within array a.


In [ ]:
import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])

# Find elements that are in b but not in a
unique_to_b = np.setdiff1d(b, a)

# Add these elements to a
a_extended = np.concatenate((a, unique_to_b))
a_extended

array([12,  5,  7, 15,  3,  1,  8,  4,  6, 11, 14, 19])

4. (7 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as
“flattening”. Transform the 4x5 array shown above in Problem 2 into a unidimensional array such that the sequence of
values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20


In [ ]:
# 4x5 array from previous tasks
array_4x5 = np.array([[ 1,  5,  9, 13, 17],
                      [ 2,  6, 10, 14, 18],
                      [ 3,  7, 11, 15, 19],
                      [ 4,  8, 12, 16, 20]])

# Transpose and then flatten the array
flattened_array = array_4x5.T.ravel()
flattened_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

5. (8 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a
NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.
The original source of the data set contains an overview of its content:

In [14]:
import pandas
import numpy as np
# suppress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/Sree199920/DAV5400/main/M3_Data_1040247735.csv').to_numpy()
# verify you have an ndarray object
type(nyc_water)
type_of_nyc_water, nyc_water[:5]  # Displaying the type and first 5 rows of the data for verification



(numpy.ndarray,
 array([[   1979., 7102100.,    1512.,     213.],
        [   1980., 7071639.,    1506.,     213.],
        [   1981., 7089241.,    1309.,     185.],
        [   1982., 7109105.,    1382.,     194.],
        [   1983., 7181224.,    1424.,     198.]]))

Which year had the maximum per capita daily water consumption?

In [15]:
import numpy as np
import pandas as pd

# Assuming nyc_water is your data in a NumPy array
# Identify the index of the maximum per capita daily water consumption
max_per_capita_idx = np.argmax(nyc_water[:, 3])

# Find the corresponding year
year_max_per_capita = nyc_water[max_per_capita_idx, 0]
year_max_per_capita

1979.0

 Add a new column to the Numpy array containing the annual change in the population of the city from year to
year. (HINT: Your new column should include the calculation of a data value for every year represented within
the data set except for the first year, which should contain a data value of ‘N/A’)

In [16]:
# Calculate the annual change in population
population_change = np.diff(nyc_water[:, 1], prepend=nyc_water[0, 1])

# Add the population change as a new column to nyc_water array
nyc_water_extended = np.column_stack((nyc_water, population_change))

# Verify the operation by displaying the first few rows of the updated array
print(nyc_water_extended[:5])

[[   1979. 7102100.    1512.     213.       0.]
 [   1980. 7071639.    1506.     213.  -30461.]
 [   1981. 7089241.    1309.     185.   17602.]
 [   1982. 7109105.    1382.     194.   19864.]
 [   1983. 7181224.    1424.     198.   72119.]]


What is the median and variance of the population of the city during the time period represented within the
data set?

In [17]:
# Calculate the median and variance of the population
population_median = np.median(nyc_water[:, 1])
population_variance = np.var(nyc_water[:, 1])

population_median, population_variance

(7947660.0, 214014109798.73172)

What was the average annual change in the population of the city?

In [18]:
# Calculate the annual change in population
population_change = np.diff(nyc_water[:, 1], prepend=nyc_water[0, 1])

# Calculate the average annual change in population
average_annual_change = np.mean(population_change[1:])  # exclude the first element (it's the same as the first population count)

average_annual_change


30867.925